/// Flutter icons Loading
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Loading
///      fonts:
///       - asset: fonts/Loading.ttf
///
/// 
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
///
import 'package:flutter/widgets.dart';

class Loading {
  Loading._();

  static const _kFontFam = 'Loading';
  static const String _kFontPkg = null;

  static const IconData spin4 = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
